name: "Research XS/S Linear Tickets"
on:
  push:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
    inputs:
      num_tickets:
        description: "Maximum number of tickets to try and fetch"
        required: false
        type: string
        default: "10"

jobs:
  fetch-tickets:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup bun"
        uses: oven-sh/setup-bun@v2

      - name: "Build actions"
        run: cd .github/actions/fetch-researchable-tickest && bun install

      - name: "Fetch Researchable Linear Tickets"
        uses: ./.github/actions/fetch-researchable-tickets
        with:
          num_tickets: ${{ inputs.num_tickets }}
